version: "3"

services:
  vnet_devel:
    build: .
    command: /usr/sbin/sshd -D
    ports:
      - '10022:22'
      - '10080:80'
      - '18080:8080'
    expose:
      - '10022'
      - '10080'
      - '18080'
